version: '3'
services:
  db:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - ${PWD}/mytest.sql:/docker-entrypoint-initdb.d/mydb.sql
    environment:
      POSTGRES_PASSWORD: postgres
  flaskapp:
    build: .
    ports:
      - "5001:5001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mytest
      DB_HOST: my-postgres-container
    volumes:
      - ${PWD}:/app
    depends_on:
      - db
volumes:
  postgres:
    name: my-volume